name: Deploy Development
on:
  push:
    branches:
      - development
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '14.4.x'

    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${{github.base_ref}}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo ${{ github.event.pull_request.title }}

    - name: Enviar Notificaion
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELGRAM_CHATID }}
        token: ${{ secrets.TELEGRAM_BOTTOKEN }}
        args: Merge ${{ steps.vars.outputs.short_ref }} into Development
